"""inventory-reorder: a demand-driven inventory environment (HUD v6).

One autonomous-business loop: an agent manages reordering for a small catalog of
SKUs across a simulated season. It reads each SKU's costs, lead time, and recent
demand, then submits a reorder policy (order-up-to-S target levels). The verifier
runs the full seeded season deterministically and scores the agent on a TRUE REWARD
FUNCTION — holding cost vs. stockout cost — normalized between a do-nothing floor
and an order-up-to-S reference. >1.0 means it beat the reference heuristic.

Mirrors the autobiz-kernel pattern: the agent submits once via a tool, and a
deterministic, offline, key-free verifier runs the hidden dynamics (stochastic but
seeded demand, planted spikes) to produce the score. No memorization shortcut: the
demand the agent is scored on is generated by the verifier, not shown in full.
"""

# NOTE: no `from __future__ import annotations` — same reason as the template:
# it breaks the @env.template manifest path. Keep annotations as real objects.
import asyncio
import contextlib
import json
import logging
import socket
import sys
from collections.abc import AsyncGenerator
from typing import Any

from hud import Environment
from hud.capabilities import Capability
from hud.graders import EvaluationResult

from environment import InventoryEnv, SeasonConfig, SKUConfig
from baselines import do_nothing_policy, make_order_up_to_s
from grader import run_episode
from sequential import SequentialSeason, run_sequential

logging.basicConfig(stream=sys.stderr, level=logging.INFO,
                    format="[%(levelname)s] %(name)s | %(message)s")
for noisy in ("FastMCP", "mcp"):
    logging.getLogger(noisy).setLevel(logging.WARNING)
logger = logging.getLogger("inventory")

env = Environment(name="inventory-reorder")

# ── substrate: the active task's season config + the agent's submitted policy ──
# Set at the top of each @env.template (per-episode), read by tools + verifier.
_SEASON: SeasonConfig | None = None
_POLICY: dict[str, float] | None = None   # {sku_name: target_S} submitted by the agent
_OPT_CACHE: dict[int, dict[str, float]] = {}   # season seed -> near-optimal targets (computed once)

# sequential-task state: a live SequentialSeason the agent drives via tools
_SEQ = None                                # SequentialSeason instance for the active episode
_SEQ_INTERVAL: int = 7                     # decision interval for the sequential task (weekly)

_HOST = "127.0.0.1"
_MCP_PORT: int | None = None
_MCP_SERVER_TASK: asyncio.Task[None] | None = None


# ── verifier (deterministic, offline, key-free) ───────────────────────────────


def _policy_from_targets(targets: dict[str, float]):
    """Turn submitted order-up-to-S targets into a policy callable the sim can run."""
    # reuse the verified order-up-to-S baseline machinery
    return make_order_up_to_s({k: float(v) for k, v in targets.items()})


def _optimal_targets(season: SeasonConfig) -> dict[str, float]:
    """Find near-optimal order-up-to-S per SKU by coordinate descent.

    This is the reference the agent is scored against: score 1.0 = matches the best
    achievable order-up-to-S policy. Per-SKU sweep then a refinement pass; cheap
    (a few dozen short episodes) and deterministic, so it's computed once and cached.
    """
    if season.seed in _OPT_CACHE:
        return _OPT_CACHE[season.seed]

    # start each SKU at a reasonable guess, then sweep each independently holding
    # the others fixed (one coordinate-descent pass is plenty — SKUs are independent
    # in cost, so the per-SKU optima don't interact).
    targets = {s.name: float(s.base_demand * (s.lead_time + 2)) for s in season.skus}
    for s in season.skus:
        best_S, best_cost = targets[s.name], float("inf")
        # search a wide range relative to this SKU's demand
        hi = int(s.base_demand * (s.lead_time + 10)) + 5
        for S in range(0, hi + 1, max(1, hi // 40)):
            trial = dict(targets)
            trial[s.name] = float(S)
            cost = run_episode(season, make_order_up_to_s(trial))
            if cost < best_cost:
                best_cost, best_S = cost, float(S)
        targets[s.name] = best_S

    _OPT_CACHE[season.seed] = targets
    return targets


def _score() -> tuple[float, dict[str, Any]]:
    """Run the full season for: agent policy, do-nothing floor, near-optimal reference.

    Returns normalized reward = (agent - floor) / (optimal - floor), clamped to [0, 1].
    1.0 = matches the best achievable order-up-to-S policy; 0.0 = no better than never
    ordering (or worse). The raw, unclamped score is kept in info for transparency.
    """
    assert _SEASON is not None
    info: dict[str, Any] = {}
    if _POLICY is None:
        return 0.0, {"reason": "No reorder policy submitted."}

    opt_targets = _optimal_targets(_SEASON)

    agent_cost = run_episode(_SEASON, _policy_from_targets(_POLICY))
    floor_cost = run_episode(_SEASON, do_nothing_policy)
    opt_cost = run_episode(_SEASON, make_order_up_to_s(opt_targets))

    agent_r, floor_r, opt_r = -agent_cost, -floor_cost, -opt_cost
    denom = opt_r - floor_r
    raw = 0.0 if denom == 0 else (agent_r - floor_r) / denom
    raw = float(raw)
    reward = float(max(0.0, min(1.0, raw)))    # clean [0, 1]: fraction of optimal

    info.update({
        "agent_cost": float(round(float(agent_cost), 1)),
        "donothing_cost": float(round(float(floor_cost), 1)),
        "optimal_cost": float(round(float(opt_cost), 1)),
        "fraction_of_optimal": round(reward, 3),
        "raw_score": round(raw, 3),            # unclamped: negative => worse than do-nothing
        "reason": (f"agent {float(agent_cost):.0f} vs optimal {float(opt_cost):.0f} "
                   f"vs do-nothing {float(floor_cost):.0f} -> {reward:.2f} of optimal"),
    })
    return reward, info


# ── tools (served over the mcp capability) ────────────────────────────────────


async def read_catalog() -> dict[str, Any]:
    """The SKUs you manage: per-SKU costs, lead time, starting stock, and season length.

    Use this to reason about each SKU's holding vs. stockout tradeoff and lead time
    before choosing target stock levels. The true demand distribution is hidden.
    """
    assert _SEASON is not None
    return {
        "season_length": _SEASON.season_length,
        "skus": [
            {
                "name": s.name,
                "init_stock": s.init_stock,
                "holding_rate": s.holding_rate,
                "stockout_penalty": s.stockout_penalty,
                "unit_cost": s.unit_cost,
                "lead_time": s.lead_time,
            }
            for s in _SEASON.skus
        ],
    }


async def peek_recent_demand(days: int = 10) -> dict[str, Any]:
    """A sample of early-season demand per SKU, to calibrate your targets.

    Returns the first `days` days of realized demand for each SKU. This is a hint,
    not the full season — later demand (including spikes) is hidden and is what you
    are scored on. Estimate the level and variability, then set targets accordingly.
    """
    assert _SEASON is not None
    probe = InventoryEnv(_SEASON)
    days = max(1, min(int(days), _SEASON.season_length))
    return {
        "days_shown": days,
        "demand": {
            s.name: probe.demand[:days, j].tolist()
            for j, s in enumerate(_SEASON.skus)
        },
    }


async def submit_policy(targets: dict[str, float]) -> dict[str, Any]:
    """Submit your reorder policy as order-up-to-S target levels, one per SKU.

    Each day, for each SKU, the system orders enough to bring (on-hand + in-transit)
    up to your target S. Higher S guards against stockouts but raises holding cost;
    lower S saves holding cost but risks stockouts. There is an interior optimum.

    Args:
        targets: mapping of SKU name -> target stock level S (a number >= 0).
    """
    global _POLICY
    assert _SEASON is not None
    names = {s.name for s in _SEASON.skus}
    missing = names - set(targets)
    if missing:
        return {"accepted": False, "reason": f"Missing targets for: {', '.join(sorted(missing))}."}
    try:
        _POLICY = {k: float(v) for k, v in targets.items() if k in names}
    except (TypeError, ValueError):
        return {"accepted": False, "reason": "Targets must be numbers."}
    return {"accepted": True, "reason": "Policy recorded; it will be evaluated over the full hidden season."}


# ── sequential task: tools + scoring ──────────────────────────────────────────
# The agent drives the season live: get_state() to observe, place_order() to act
# and advance one decision period (a week). It repeats until the season ends.


def _seq_state_payload(state: dict) -> dict[str, Any]:
    """Shape a SequentialSeason state into a clean tool response (native types)."""
    if state is None:
        return {"season_over": True}
    skus = {}
    for name, s in state["skus"].items():
        skus[name] = {
            "on_hand": int(s["on_hand"]),
            "sold_last_k_days": int(s["sold_last_k_days"]),
            "in_transit": [{"arrives_in": int(o["arrives_in"]), "qty": int(o["qty"])}
                           for o in s["in_transit"]],
            "holding_rate": float(s["holding_rate"]),
            "stockout_penalty": float(s["stockout_penalty"]),
            "unit_cost": float(s["unit_cost"]),
            "lead_time": int(s["lead_time"]),
        }
    return {
        "season_over": False,
        "day": int(state["day"]),
        "days_remaining": int(state["days_remaining"]),
        "decision_interval_days": int(state["decision_interval"]),
        "skus": skus,
    }


async def get_state() -> dict[str, Any]:
    """Observe the current decision point: per-SKU on-hand stock, recent sales,
    in-transit orders, costs, and how many days remain. Call this each period
    before deciding how much to order."""
    assert _SEQ is not None
    return _seq_state_payload(_SEQ._state())


async def place_order(orders: dict[str, float]) -> dict[str, Any]:
    """Order a quantity per SKU for this period, then advance one week. Returns
    the new state and the cost incurred over the week just simulated.

    Order what you need to cover demand over the coming weeks given lead time —
    too much wastes holding cost, too little stocks out. You will see the result
    and can adjust next week. Demand spikes may appear; react when you see them.

    Args:
        orders: mapping of SKU name -> order quantity (>= 0). Omit a SKU to order 0.
    """
    assert _SEQ is not None and _SEASON is not None
    if _SEQ.done:
        return {"season_over": True, "reason": "The season has ended."}
    names = {s.name for s in _SEASON.skus}
    try:
        clean = {k: max(0, int(v)) for k, v in orders.items() if k in names}
    except (TypeError, ValueError):
        return {"accepted": False, "reason": "Order quantities must be numbers."}
    state, period_cost = _SEQ.step(clean)
    return {
        "accepted": True,
        "week_cost": round(float(period_cost), 1),
        "cumulative_cost": round(float(_SEQ.total_cost), 1),
        "next_state": _seq_state_payload(state),
    }


_SEQ_OPT_CACHE: dict[tuple, dict[str, float]] = {}  # (seed, interval) -> weekly base-stock targets


def _sequential_optimal(season: SeasonConfig, interval: int) -> dict[str, float]:
    """Near-optimal base-stock targets for the SEQUENTIAL (periodic-review) setting.

    The one-shot optimum under-provisions here: with weekly review, each order must
    cover demand until the NEXT review plus the lead time, so targets run higher.
    Coordinate-descent per SKU at the actual decision interval. Cached per
    (seed, interval). This is the reference 1.0 means — the best weekly policy."""
    key = (season.seed, interval)
    if key in _SEQ_OPT_CACHE:
        return _SEQ_OPT_CACHE[key]
    targets = {s.name: float(s.base_demand * (interval + s.lead_time)) for s in season.skus}
    for s in season.skus:
        best_S, best_cost = targets[s.name], float("inf")
        hi = int(s.base_demand * (interval + s.lead_time + 12)) + 5
        for S in range(0, hi + 1, max(1, hi // 40)):
            trial = dict(targets); trial[s.name] = float(S)
            cost = run_sequential(season, lambda st, t=trial: make_order_up_to_s(t)(st), interval=interval)
            if cost < best_cost:
                best_cost, best_S = cost, float(S)
        targets[s.name] = best_S
    _SEQ_OPT_CACHE[key] = targets
    return targets


def _seq_score() -> tuple[float, dict[str, Any]]:
    """Score the completed sequential season: normalize the agent's total cost
    between a do-nothing floor and a weekly-tuned order-up-to-S optimum, both run
    sequentially at the same decision interval. Same [0,1] fraction-of-optimal."""
    assert _SEASON is not None and _SEQ is not None
    info: dict[str, Any] = {}
    if _SEQ.decisions_made == 0:
        return 0.0, {"reason": "No orders were ever placed."}

    agent_cost = float(_SEQ.total_cost)
    floor_cost = run_sequential(_SEASON, lambda st: {}, interval=_SEQ_INTERVAL)
    opt_targets = _sequential_optimal(_SEASON, _SEQ_INTERVAL)  # weekly-tuned reference
    opt_cost = run_sequential(
        _SEASON,
        lambda st: make_order_up_to_s(opt_targets)(st),
        interval=_SEQ_INTERVAL,
    )

    agent_r, floor_r, opt_r = -agent_cost, -floor_cost, -opt_cost
    denom = opt_r - floor_r
    raw = 0.0 if denom == 0 else (agent_r - floor_r) / denom
    raw = float(raw)
    reward = float(max(0.0, min(1.0, raw)))

    info.update({
        "agent_cost": round(agent_cost, 1),
        "donothing_cost": round(float(floor_cost), 1),
        "optimal_cost": round(float(opt_cost), 1),
        "fraction_of_optimal": round(reward, 3),
        "raw_score": round(raw, 3),
        "decisions_made": int(_SEQ.decisions_made),
        "reason": (f"agent {agent_cost:.0f} vs optimal {opt_cost:.0f} "
                   f"vs do-nothing {floor_cost:.0f} -> {reward:.2f} of optimal "
                   f"over {_SEQ.decisions_made} weekly decisions"),
    })
    return reward, info


# ── mcp capability lifecycle (identical pattern to the template) ───────────────


def _free_port() -> int:
    with socket.socket() as s:
        s.bind((_HOST, 0))
        return int(s.getsockname()[1])


async def _listening(port: int, timeout: float = 15.0) -> None:
    loop = asyncio.get_running_loop()
    deadline = loop.time() + timeout
    while loop.time() < deadline:
        try:
            socket.create_connection((_HOST, port), timeout=0.5).close()
            return
        except OSError:
            await asyncio.sleep(0.1)
    raise RuntimeError(f"mcp server never came up on {_HOST}:{port}")


@env.initialize
async def _up() -> None:
    from fastmcp import FastMCP
    global _MCP_PORT, _MCP_SERVER_TASK
    if _MCP_SERVER_TASK is None:
        server = FastMCP(name="inventory-tools")
        for tool in (read_catalog, peek_recent_demand, submit_policy,
                     get_state, place_order):
            server.tool(tool)
        _MCP_PORT = _free_port()
        _MCP_SERVER_TASK = asyncio.create_task(
            server.run_async(transport="http", host=_HOST, port=_MCP_PORT, show_banner=False)
        )
        await _listening(_MCP_PORT)
    env.add_capability(Capability.mcp(name="inventory", url=f"http://{_HOST}:{_MCP_PORT}/mcp"))


@env.shutdown
async def _down() -> None:
    global _MCP_SERVER_TASK
    if _MCP_SERVER_TASK is not None:
        _MCP_SERVER_TASK.cancel()
        with contextlib.suppress(asyncio.CancelledError):
            await _MCP_SERVER_TASK
        _MCP_SERVER_TASK = None


# ── season configs (the three difficulty variants) ────────────────────────────

_EASY_SEASON = SeasonConfig(
    skus=[SKUConfig(name="widget", base_demand=10, holding_rate=0.5,
                    stockout_penalty=5.0, unit_cost=1.0, lead_time=3,
                    init_stock=30, spike_days=[40], spike_mult=2.5)],
    season_length=60, seasonality_amp=0.15, seed=11,
)

_MEDIUM_SEASON = SeasonConfig(
    skus=[
        SKUConfig(name="widget", base_demand=10, holding_rate=0.5,
                  stockout_penalty=5.0, unit_cost=1.0, lead_time=3,
                  init_stock=30, spike_days=[35], spike_mult=3.0),
        SKUConfig(name="gadget", base_demand=6, holding_rate=0.8,
                  stockout_penalty=4.0, unit_cost=1.5, lead_time=5,
                  init_stock=20, spike_days=[35], spike_mult=3.0),
        SKUConfig(name="gizmo", base_demand=15, holding_rate=0.3,
                  stockout_penalty=6.0, unit_cost=0.8, lead_time=2,
                  init_stock=40, spike_days=[50], spike_mult=2.5),
    ],
    season_length=60, seasonality_amp=0.3, seed=22,
)

_HARD_SEASON = SeasonConfig(
    skus=[
        SKUConfig(name="widget", base_demand=10, holding_rate=0.7,
                  stockout_penalty=4.0, unit_cost=1.0, lead_time=6,
                  init_stock=25, spike_days=[20, 45], spike_mult=3.5),
        SKUConfig(name="gadget", base_demand=6, holding_rate=0.9,
                  stockout_penalty=3.5, unit_cost=1.5, lead_time=7,
                  init_stock=18, spike_days=[20, 45], spike_mult=3.0),
        SKUConfig(name="gizmo", base_demand=15, holding_rate=0.5,
                  stockout_penalty=4.5, unit_cost=0.8, lead_time=5,
                  init_stock=35, spike_days=[30], spike_mult=4.0),
        SKUConfig(name="sprocket", base_demand=4, holding_rate=1.0,
                  stockout_penalty=3.0, unit_cost=2.0, lead_time=8,
                  init_stock=12, spike_days=[45], spike_mult=3.0),
        SKUConfig(name="cog", base_demand=20, holding_rate=0.4,
                  stockout_penalty=5.0, unit_cost=0.6, lead_time=4,
                  init_stock=50, spike_days=[20, 30], spike_mult=2.5),
    ],
    season_length=60, seasonality_amp=0.4, seed=33,
)


# ── task templates ────────────────────────────────────────────────────────────
# One named @env.template per difficulty. HUD discovers tasks by NAME, and a task
# is produced by CALLING the template (in tasks.py) — mirroring the autobiz template
# where `_one_deal = one_deal(prompt=...)`. Each template binds its own season, then
# runs the shared verifier. The prompt is passed in from tasks.py.

async def _run_season(season: SeasonConfig, name: str, prompt: str) -> AsyncGenerator[Any, Any]:
    """Shared episode body: bind the season, let the agent act, then score."""
    global _SEASON, _POLICY
    _SEASON = season
    _POLICY = None

    yield prompt  # the agent works through the tools; its text reply isn't graded

    reward, info = _score()
    logger.info("inventory[%s] reward=%.3f (%s)", name, reward, info.get("reason", ""))
    yield EvaluationResult(reward=reward, content=info.get("reason", ""), info=info)


@env.template()
async def inventory_easy(prompt: str) -> AsyncGenerator[Any, Any]:
    """Easy: 1 SKU, stable demand, short lead time."""
    async for item in _run_season(_EASY_SEASON, "inventory_easy", prompt):
        yield item


@env.template()
async def inventory_medium(prompt: str) -> AsyncGenerator[Any, Any]:
    """Medium: 3 SKUs, mild seasonality, one demand spike."""
    async for item in _run_season(_MEDIUM_SEASON, "inventory_medium", prompt):
        yield item


@env.template()
async def inventory_hard(prompt: str) -> AsyncGenerator[Any, Any]:
    """Hard: 5 SKUs, long lead times, two spikes, tighter cost ratio."""
    async for item in _run_season(_HARD_SEASON, "inventory_hard", prompt):
        yield item


@env.template()
async def inventory_sequential(prompt: str) -> AsyncGenerator[Any, Any]:
    """Sequential: the agent reorders week-by-week, observing state and adapting
    to demand as the season unfolds (vs. the one-shot tasks' single static policy)."""
    global _SEQ, _SEASON, _SEQ_INTERVAL
    _SEASON = _MEDIUM_SEASON          # 3 SKUs with a mid-season spike — good for adapting
    _SEQ_INTERVAL = 7                 # weekly decisions (~9 over the 60-day season)
    _SEQ = SequentialSeason(_SEASON, interval=_SEQ_INTERVAL)
    _SEQ.reset()

    yield prompt  # the agent drives the season via get_state / place_order

    reward, info = _seq_score()
    logger.info("inventory_sequential reward=%.3f (%s)", reward, info.get("reason", ""))
    yield EvaluationResult(reward=reward, content=info.get("reason", ""), info=info)

